language: c

compiler:
  - gcc

install:
  - pip install --user cpp-coveralls

before_script:
  - uname -a

script:
  - make clean all
  - make clean test

after_success:
  # upload to codecov
  - curl -s https://codecov.io/bash | bash -s - -X gcov
  # upload to coveralls
  - coveralls -n -i src
